#!/bin/bash
# 프로젝트 디렉토리 구조 확인

echo "📂 프로젝트 디렉토리 구조"
echo "================================"
echo ""
echo "hexa-indexer/"
echo "├── 📄 build.gradle.kts"
echo "├── 📄 settings.gradle.kts"
echo "├── 📄 docker-compose.yml"
echo "├── 📄 Dockerfile"
echo "├── 📄 README.md"
echo "├── 📄 STRUCTURE.md"
echo "└── 📁 src/"
echo "    ├── 📁 main/"
echo "    │   ├── 📁 kotlin/"
echo "    │   │   └── 📁 com/example/kafkaes/"
echo "    │   │       ├── 📁 domain/"
echo "    │   │       │   ├── 📁 model/              ← 도메인 모델"
echo "    │   │       │   ├── 📁 port/"
echo "    │   │       │   │   ├── 📁 inbound/        ← 외부 → 도메인"
echo "    │   │       │   │   └── 📁 outbound/       ← 도메인 → 외부"
echo "    │   │       │   └── 📁 service/            ← 비즈니스 로직"
echo "    │   │       ├── 📁 adapter/"
echo "    │   │       │   ├── 📁 inbound/"
echo "    │   │       │   │   └── 📁 kafka/          ← Kafka Consumer"
echo "    │   │       │   └── 📁 outbound/"
echo "    │   │       │       └── 📁 elasticsearch/  ← ES Indexer"
echo "    │   │       └── 📁 config/                 ← 설정"
echo "    │   └── 📁 resources/"
echo "    └── 📁 test/kotlin/"
echo ""
echo "✅ 디렉토리 구조 생성 완료!"